#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef ZCHATCOMPONENT_SWIFT_H
#define ZCHATCOMPONENT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AppKit;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import ZoomKit;
@import ZoomUnit;
#endif

#import <zChatComponent/zChatComponent.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="zChatComponent",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSCoder;

SWIFT_CLASS_NAMED("AddStickerView")
@interface ZMAddStickerView : ZMBaseView
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ZMChatMsgItemInfo;
@class NSBundle;

SWIFT_CLASS("_TtC14zChatComponent33AppMessageBaseComponentController")
@interface AppMessageBaseComponentController : NSViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidDisappear;
- (nonnull instancetype)initWithNibName:(NSNibName _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class NSAttributedString;
@class NSString;

SWIFT_CLASS_NAMED("AppMessageAlertComponentController")
@interface ZMCAppMessageAlertComponentController : AppMessageBaseComponentController
/// The attributed string to be displayed in the alert.
@property (nonatomic, strong) NSAttributedString * _Nullable attributedString;
/// Level of the alert.
@property (nonatomic) ZMCommonAppAlertLevel level;
/// A Boolean value that indicates whether a close button is shown.
@property (nonatomic) BOOL closable;
@property (nonatomic, copy) NSString * _Nullable eventID;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayout;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end



@class ZMCommonAppActionItem;

SWIFT_CLASS_NAMED("AppMessageButtonComponentController")
@interface ZMCAppMessageButtonComponentController : AppMessageBaseComponentController
@property (nonatomic, copy) NSString * _Nonnull labelText;
@property (nonatomic, copy) NSString * _Nullable iconURL;
@property (nonatomic) ZMCommonAppActionButtonStyle style;
@property (nonatomic) BOOL isMoreButton;
@property (nonatomic) BOOL buttonEnabled;
@property (nonatomic, strong) ZMCommonAppActionItem * _Nullable action;
@property (nonatomic, copy) NSArray<ZMCommonAppActionItem *> * _Nullable actions;
@property (nonatomic, copy) NSString * _Nullable eventID;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end


@class ZMCommonAppCheckboxItem;

SWIFT_CLASS_NAMED("AppMessageCheckboxComponentController")
@interface ZMCAppMessageCheckboxComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) ZMCommonAppCheckboxItem * _Nullable item;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayout;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end



@class ZMCAppMessageRowComponentController;
@class ZMCAppMessagePickerComponentController;
@class ZMCAppMessageTextComponentController;
@class ZMCAppMessageImageComponentController;
@class ZMCAppMessageProgressIndicatorComponentController;
@class ZMCAppMessageDividerComponentController;
@class ZMCAppMessageRadioButtonComponentController;
@class ZMCAppMessageExpanderComponentController;
@class ZMCAppMessageFilePreviewComponentController;
@class ZMCAppMessageFileComponentController;
@class ZMCAppMessageMeetingCardComponentController;

SWIFT_CLASS_NAMED("AppMessageComponentFactory")
@interface ZMCAppMessageComponentFactory : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZMCAppMessageComponentFactory * _Nonnull sharedFactory;)
+ (ZMCAppMessageComponentFactory * _Nonnull)sharedFactory SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageRowComponentController * _Nonnull)dequeueOrCreateRowComponent SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageButtonComponentController * _Nonnull)dequeueOrCreateButtonComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessagePickerComponentController * _Nonnull)dequeueOrCreatePickerComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageTextComponentController * _Nonnull)dequeueOrCreateTextComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageImageComponentController * _Nonnull)dequeueOrCreateImageComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageProgressIndicatorComponentController * _Nonnull)dequeueOrCreateProgressIndicatorComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageDividerComponentController * _Nonnull)dequeueOrCreateDividerComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageCheckboxComponentController * _Nonnull)dequeueOrCreateCheckboxComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageRadioButtonComponentController * _Nonnull)dequeueOrCreateRadioButtonComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageAlertComponentController * _Nonnull)dequeueOrCreateAlertComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageExpanderComponentController * _Nonnull)dequeueOrCreateExpanderComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageFilePreviewComponentController * _Nonnull)dequeueOrCreateFilePreviewComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageFileComponentController * _Nonnull)dequeueOrCreateFileComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (ZMCAppMessageMeetingCardComponentController * _Nonnull)dequeueOrCreateMeetingCardComponentWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)removeAllCache;
- (void)recycleComponentFromViewController:(NSViewController * _Nonnull)viewController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class ZMCommonAppDialogData;

SWIFT_PROTOCOL_NAMED("AppMessageComponentHost")
@protocol ZMCAppMessageComponentHost <NSObject>
- (void)openChatAppWithDialogAction:(ZMCommonAppDialogData * _Nonnull)dialogData messageTemplateIndex:(NSInteger)messageTemplateIndex;
- (void)noteComponentLayoutChanged;
- (void)reloadContents;
- (void)showCommonAppEditFailedToast;
@end

@class NSColor;

SWIFT_CLASS_NAMED("AppMessageDividerComponentController")
@interface ZMCAppMessageDividerComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) NSColor * _Nullable lineColor;
@property (nonatomic) BOOL bold;
@property (nonatomic) BOOL dotted;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("AppMessageExpanderComponentController")
@interface ZMCAppMessageExpanderComponentController : AppMessageBaseComponentController
@property (nonatomic) NSInteger numberOfAttachments;
@property (nonatomic) BOOL expanded;
@property (nonatomic) NSInteger attachmentIndex;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end


@class NSImage;
@class ZMChatFileItemSwiftAdaptor;

SWIFT_CLASS_NAMED("AppMessageFileComponentController")
@interface ZMCAppMessageFileComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) NSAttributedString * _Nullable fileName;
@property (nonatomic, strong) NSAttributedString * _Nullable fileDescription;
@property (nonatomic, copy) NSString * _Nullable resourceURL;
@property (nonatomic, strong) NSImage * _Nullable iconImage;
@property (nonatomic, strong) NSImage * _Nullable image;
@property (nonatomic, strong) ZMChatFileItemSwiftAdaptor * _Nullable fileItem;
@property (nonatomic) uint64_t size;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end




@class ZMCommonAppTemplateFileItem;

SWIFT_CLASS_NAMED("AppMessageFilePreviewComponentController")
@interface ZMCAppMessageFilePreviewComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) ZMCommonAppTemplateFileItem * _Nullable item;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayout;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("AppMessageImageComponentController")
@interface ZMCAppMessageImageComponentController : AppMessageBaseComponentController
@property (nonatomic, copy) NSString * _Nullable imageURLString;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
@end


@class NSView;
@class NSTextContainer;
@protocol ZMMessageCellViewDelegate;
@class ZMBaseMessageCellView;

SWIFT_CLASS_NAMED("AppMessageLazyViewCell")
@interface ZMCAppMessageLazyViewCell : ZMPTCommonBaseCell <ZMViewAttachmentCellProtocol>
@property (nonatomic, copy) NSViewController * _Nonnull (^ _Nonnull builder)(void);
@property (nonatomic, readonly, strong) NSView * _Nullable imageView;
@property (nonatomic, readonly, strong) NSView * _Nullable view;
@property (nonatomic, readonly) BOOL needFocusRing;
- (nonnull instancetype)initWithBuilder:(NSViewController * _Nonnull (^ _Nonnull)(void))builder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (NSRect)cellFrameForTextContainer:(NSTextContainer * _Nonnull)textContainer proposedLineFragment:(NSRect)lineFrag glyphPosition:(NSPoint)position characterIndex:(NSUInteger)charIndex SWIFT_WARN_UNUSED_RESULT;
- (void)drawWithFrame:(NSRect)cellFrame inView:(NSView * _Nullable)controlView;
- (void)cleanUp;
- (void)attachDelegate:(id <ZMMessageCellViewDelegate> _Nullable)delegate ofMessageCellView:(ZMBaseMessageCellView * _Nonnull)cellView;
- (NSString * _Nullable)copyString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initTextCell:(NSString * _Nonnull)string SWIFT_UNAVAILABLE;
- (nonnull instancetype)initImageCell:(NSImage * _Nullable)image SWIFT_UNAVAILABLE;
@end

@class ZMCommonAppMeetingCardItem;

SWIFT_CLASS_NAMED("AppMessageMeetingCardComponentController")
@interface ZMCAppMessageMeetingCardComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) ZMCommonAppMeetingCardItem * _Nullable item;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidAppear;
- (void)viewDidDisappear;
- (void)viewDidLayout;
@end




@interface ZMCAppMessageMeetingCardComponentController (SWIFT_EXTENSION(zChatComponent)) <ZMClockWatcher>
- (void)minuteChanged;
@end









@class ZMCommonAppSelectItem;
@class ZMCommonAppDateTimePickerItem;

SWIFT_CLASS_NAMED("AppMessagePickerComponentController")
@interface ZMCAppMessagePickerComponentController : AppMessageBaseComponentController
- (void)configureWithSelectItem:(ZMCommonAppSelectItem * _Nonnull)item displayedAsAccessory:(BOOL)displayedAsAccessory;
- (void)configureWithDateTimePickerItem:(ZMCommonAppDateTimePickerItem * _Nonnull)item;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("AppMessageProgressIndicatorComponentController")
@interface ZMCAppMessageProgressIndicatorComponentController : AppMessageBaseComponentController
@property (nonatomic) double value;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end


@class ZMCommonAppRadioButtonItem;

SWIFT_CLASS_NAMED("AppMessageRadioButtonComponentController")
@interface ZMCAppMessageRadioButtonComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) ZMCommonAppRadioButtonItem * _Nullable item;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayout;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("AppMessageRowComponentController")
@interface ZMCAppMessageRowComponentController : NSViewController
@property (nonatomic, readonly, copy) NSArray<NSViewController *> * _Nonnull childComponents;
@property (nonatomic) CGFloat spacing;
@property (nonatomic) ZMKFlexboxAlign alignItems;
@property (nonatomic) BOOL wrap;
@property (nonatomic) BOOL adaptive;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidLayout;
- (void)addChildComponent:(NSViewController * _Nonnull)childComponent flexible:(BOOL)flexible;
- (nonnull instancetype)initWithNibName:(NSNibName _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS_NAMED("AppMessageTextComponentController")
@interface ZMCAppMessageTextComponentController : AppMessageBaseComponentController
@property (nonatomic, strong) NSAttributedString * _Nullable attributedString;
- (void)loadView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithMessageInfo:(ZMChatMsgItemInfo * _Nonnull)messageInfo index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("AttachmentLabel")
@interface ZMAttachmentLabel : ZMLabel
@property (nonatomic) NSRect frame;
@property (nonatomic) NSRect bounds;
- (void)setNeedsDisplayInRect:(NSRect)invalidRect;
- (void)drawRect:(NSRect)dirtyRect;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ZMBaseTextAttachmentCell;

@interface ZMAttachmentLabel (SWIFT_EXTENSION(zChatComponent)) <ZMBaseTextProtocol>
- (void)addAttachmentCell:(ZMBaseTextAttachmentCell * _Nonnull)attachmentCell withFrame:(CGRect)frame;
@end

@class PZMAvatarPresenceView;

SWIFT_CLASS_NAMED("AvatarPresenceViewHelper")
@interface ZMCAvatarPresenceViewHelper : NSObject
+ (void)setPresence:(ZMIMBuddyPresenceType)presenceType forAvatarPresenceView:(PZMAvatarPresenceView * _Nonnull)view;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CenterVerticalAlignment, open) {
  CenterVerticalAlignmentLeft = 0,
  CenterVerticalAlignmentRight = 1,
  CenterVerticalAlignmentCenter = 2,
};


SWIFT_CLASS_NAMED("CenterVerticalLabel")
@interface ZMCenterVerticalLabel : NSView
@property (nonatomic, readonly, copy) NSString * _Nonnull stringValue;
@property (nonatomic, readonly) CGFloat fontSize;
@property (nonatomic, strong) NSColor * _Nonnull color;
@property (nonatomic) enum CenterVerticalAlignment alignment;
@property (nonatomic, copy) NSString * _Nullable fontName;
- (NSString * _Nullable)accessibilityLabel SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSSize intrinsicContentSize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)updateStringValue:(NSString * _Nullable)stringValue;
- (void)updateFontSize:(CGFloat)fontSize;
- (void)updateStringValue:(NSString * _Nullable)stringValue fontSize:(CGFloat)fontSize;
- (void)drawRect:(NSRect)dirtyRect;
- (NSView * _Nullable)hitTest:(NSPoint)point SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect SWIFT_UNAVAILABLE;
@end

@class NSCollectionView;
@class ZMCollectionViewWaterfallLayout;

SWIFT_PROTOCOL_NAMED("CollectionViewDelegateWaterfallLayout")
@protocol ZMCollectionViewDelegateWaterfallLayout <NSCollectionViewDelegateFlowLayout>
- (CGFloat)collectionView:(NSCollectionView * _Nonnull)collectionView layout:(ZMCollectionViewWaterfallLayout * _Nonnull)layout itemWidthInSection:(NSInteger)itemWidthInSection SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCollectionViewLayoutAttributes;

SWIFT_CLASS_NAMED("CollectionViewWaterfallLayout")
@interface ZMCollectionViewWaterfallLayout : NSCollectionViewFlowLayout
- (void)prepareLayout;
- (NSArray<NSCollectionViewLayoutAttributes *> * _Nonnull)layoutAttributesForElementsInRect:(NSRect)rect SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGSize collectionViewContentSize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CommonAppChannelCell")
@interface ZMPTCommonAppChannelCell : ZMPTCommonBaseCell
/// The session ID that this cell represents.
@property (nonatomic, copy) NSString * _Nullable sessionID;
/// The number that displays after the title.
/// When the number in this property is <code>0</code>, the cell doesn’t display a
/// badge. When the number is greater than <code>0</code>, a red badge with this
/// number is displayed after the title label.
@property (nonatomic) NSUInteger badgeCount;
/// A short text displayed before the badge.
/// When <code>badgeCount</code> is greater than <code>0</code>, you can set this property to
/// show a short text before the badge. This property does nothing when
/// <code>badgeCount</code> is <code>0</code>.
@property (nonatomic, copy) NSString * _Nullable badgeInformativeText;
/// The icon that displays before the title.
@property (nonatomic, strong) NSImage * _Nullable iconImage;
- (NSRect)cellFrameForTextContainer:(NSTextContainer * _Nonnull)textContainer proposedLineFragment:(NSRect)lineFrag glyphPosition:(NSPoint)position characterIndex:(NSUInteger)charIndex SWIFT_WARN_UNUSED_RESULT;
- (void)drawWithFrame:(NSRect)cellFrame inView:(NSView * _Nullable)controlView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initTextCell:(NSString * _Nonnull)string OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initImageCell:(NSImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZMPTCommonAppChannelCell (SWIFT_EXTENSION(zChatComponent)) <ZMViewAttachmentCellProtocol>
@property (nonatomic, readonly, strong) NSView * _Nullable imageView;
- (void)cleanUp;
@end

enum ZMCommonAppChannelMentionType : NSInteger;

SWIFT_CLASS_NAMED("CommonAppChannelItem")
@interface ZMCommonAppChannelItem : ZMCommonAppBaseItem
@property (nonatomic) enum ZMCommonAppChannelMentionType mentionType;
@property (nonatomic, copy) NSString * _Nullable iconType;
@property (nonatomic, copy) NSString * _Nullable sessionID;
@property (nonatomic) NSUInteger unreadCount;
@property (nonatomic) BOOL hasDraft;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ZMCommonAppChannelMentionType, "CommonAppChannelMentionType", open) {
  ZMCommonAppChannelMentionTypeNone = 0,
  ZMCommonAppChannelMentionTypeAtMe = 1,
  ZMCommonAppChannelMentionTypeAtMePlus = 2,
  ZMCommonAppChannelMentionTypeAtAll = 3,
};


SWIFT_CLASS_NAMED("CommonAppMeetingCardCell")
@interface ZMPTCommonAppMeetingCardCell : ZMPTCommonBaseCell
- (nullable instancetype)initWithMessageID:(NSString * _Nonnull)messageID sessionID:(NSString * _Nonnull)sessionID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (NSRect)cellFrameForTextContainer:(NSTextContainer * _Nonnull)textContainer proposedLineFragment:(NSRect)lineFrag glyphPosition:(NSPoint)position characterIndex:(NSUInteger)charIndex SWIFT_WARN_UNUSED_RESULT;
- (void)drawWithFrame:(NSRect)cellFrame inView:(NSView * _Nullable)controlView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initTextCell:(NSString * _Nonnull)string SWIFT_UNAVAILABLE;
- (nonnull instancetype)initImageCell:(NSImage * _Nullable)image SWIFT_UNAVAILABLE;
@end


@interface ZMPTCommonAppMeetingCardCell (SWIFT_EXTENSION(zChatComponent)) <ZMViewAttachmentCellProtocol>
@property (nonatomic, readonly, strong) NSView * _Nullable imageView;
- (void)cleanUp;
- (void)attachDelegate:(id <ZMMessageCellViewDelegate> _Nullable)delegate ofMessageCellView:(ZMBaseMessageCellView * _Nonnull)cellView;
@end

@class ZMScheduleMeetingCardView;
@class ZMScheduleMeetingInfo;

@interface ZMPTCommonAppMeetingCardCell (SWIFT_EXTENSION(zChatComponent)) <ZMScheduleMeetingCardViewDelegate>
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView joinMeeting:(NSString * _Nonnull)sessionId meetingNumber:(NSInteger)meetingNumber password:(NSString * _Nonnull)password;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView fromSession:(NSString * _Nonnull)sessionId openCMCchat:(NSString * _Nonnull)subCMCSessionId;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView viewInCalendar:(NSString * _Nonnull)calendarLink;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView copyInvitation:(NSString * _Nonnull)joinURL;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView editMeeting:(NSString * _Nonnull)sessionId meetingNumber:(NSInteger)meetingNumber occurrenceTime:(NSInteger)occurrenceTime meetingMasterEventId:(NSString * _Nonnull)meetingMasterEventId;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView deleteMeeting:(NSString * _Nonnull)sessionId meetingNumber:(NSInteger)meetingNumber occurrenceTime:(NSInteger)occurrenceTime meetingMasterEventId:(NSString * _Nonnull)meetingMasterEventId;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView joinFromARoom:(NSString * _Nonnull)sessionId meetingNumber:(NSInteger)meetingNumber;
- (void)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView moreParticipantsClicked:(ZMScheduleMeetingInfo * _Nonnull)meetingInfo;
- (BOOL)scheduleMeetingCardView:(ZMScheduleMeetingCardView * _Nonnull)scheduleMeetingCardView isInMeeting:(NSInteger)meetingNumber SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("CommonAppMeetingCardItem")
@interface ZMCommonAppMeetingCardItem : ZMCommonAppBaseItem
@property (nonatomic, copy) NSString * _Nullable messageID;
@property (nonatomic, copy) NSString * _Nullable sessionID;
@property (nonatomic) BOOL assetsCard;
@property (nonatomic) BOOL hasThumbnail;
@property (nonatomic, copy) NSString * _Nullable thumbnailURL;
@property (nonatomic, copy) NSString * _Nullable recordingDurationString;
@property (nonatomic, copy) NSString * _Nullable meetingSummary;
@property (nonatomic) ZMCommonAppPostMeetingAssetMask assets;
@property (nonatomic) ZMCommonAppPostMeetingShareBannerType shareBanner;
@property (nonatomic) ZMCommonAppPostMeetingCardHint hints;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZMCommonAppTextAreaItem;

SWIFT_CLASS_NAMED("CommonAppTextAreaCell")
@interface ZMPTCommonAppTextAreaCell : ZMPTCommonBaseCell
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull stringValue;
@property (nonatomic, strong) ZMCommonAppTextAreaItem * _Nullable textAreaItem;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (NSRect)cellFrameForTextContainer:(NSTextContainer * _Nonnull)textContainer proposedLineFragment:(NSRect)lineFrag glyphPosition:(NSPoint)position characterIndex:(NSUInteger)charIndex SWIFT_WARN_UNUSED_RESULT;
- (void)drawWithFrame:(NSRect)cellFrame inView:(NSView * _Nullable)controlView;
- (nonnull instancetype)initTextCell:(NSString * _Nonnull)string SWIFT_UNAVAILABLE;
- (nonnull instancetype)initImageCell:(NSImage * _Nullable)image SWIFT_UNAVAILABLE;
@end


@interface ZMPTCommonAppTextAreaCell (SWIFT_EXTENSION(zChatComponent)) <ZMViewAttachmentCellProtocol>
@property (nonatomic, readonly, strong) NSView * _Nullable imageView;
- (void)cleanUp;
@end

@class ZMPTCommonAppTextAreaCxxItemWrapper;

SWIFT_CLASS_NAMED("CommonAppTextAreaItem")
@interface ZMCommonAppTextAreaItem : ZMCommonAppBaseItem
@property (nonatomic, readonly, strong) ZMPTCommonAppTextAreaCxxItemWrapper * _Nonnull cxxItemWrapper;
@property (nonatomic, copy) NSString * _Nullable sessionID;
@property (nonatomic, copy) NSString * _Nullable messageID;
@property (nonatomic, copy) NSString * _Nullable eventID;
@property (nonatomic, copy) NSString * _Nullable actionID;
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nonnull value;
@property (nonatomic, readonly, copy) NSString * _Nonnull placeholder;
@property (nonatomic, readonly) BOOL multiline;
@property (nonatomic, readonly) NSInteger maximumLength;
@property (nonatomic, copy) BOOL (^ _Nullable commitHandler)(NSString * _Nonnull);
- (nonnull instancetype)initWithCxxItemWrapper:(ZMPTCommonAppTextAreaCxxItemWrapper * _Nonnull)cxxItemWrapper OBJC_DESIGNATED_INITIALIZER;
- (BOOL)commitChanges;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ZMPTCommonAppTextLayoutInfo;

SWIFT_CLASS_NAMED("CommonAppTextLayoutHelperReference")
@interface ZMPTCommonAppTextLayoutHelper : NSObject
+ (ZMPTCommonAppTextLayoutInfo * _Nonnull)layoutInfoOfAttributedString:(NSAttributedString * _Nonnull)attributedString containerSize:(CGSize)containerSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("LayoutInfo")
@interface ZMPTCommonAppTextLayoutInfo : NSObject
@property (nonatomic, readonly) NSInteger numberOfLines;
@property (nonatomic, readonly) CGRect boundingRect;
- (CGRect)usedRectForLineAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSRange)characterRangeForLineAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)drawAtPoint:(NSPoint)point;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ZMCommonAppVideoItem;

SWIFT_CLASS_NAMED("CommonAppVideoCell")
@interface ZMPTCommonAppVideoCell : ZMPTCommonBaseCell
@property (nonatomic, copy) NSString * _Nullable sessionID;
@property (nonatomic, copy) NSString * _Nullable messageID;
@property (nonatomic, strong) ZMCommonAppVideoItem * _Nullable item;
@property (nonatomic, readonly, strong) NSView * _Nonnull view;
- (NSRect)cellFrameForTextContainer:(NSTextContainer * _Nonnull)textContainer proposedLineFragment:(NSRect)lineFrag glyphPosition:(NSPoint)position characterIndex:(NSUInteger)charIndex SWIFT_WARN_UNUSED_RESULT;
- (void)drawWithFrame:(NSRect)cellFrame inView:(NSView * _Nullable)controlView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initTextCell:(NSString * _Nonnull)string OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initImageCell:(NSImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZMPTCommonAppVideoCell (SWIFT_EXTENSION(zChatComponent)) <ZMViewAttachmentCellProtocol>
@property (nonatomic, readonly, strong) NSView * _Nullable imageView;
- (void)cleanUp;
@end

@class NSURL;
@class ZMAppMarkdownText;
@class ZMCBotInlineVideoPreviewAppContext;

SWIFT_CLASS_NAMED("CommonAppVideoItem")
@interface ZMCommonAppVideoItem : ZMCommonAppBaseItem
@property (nonatomic, copy) NSURL * _Nullable thumbnailURL;
@property (nonatomic, copy) NSString * _Nullable providerName;
@property (nonatomic, copy) NSURL * _Nullable providerIconUrl;
@property (nonatomic, copy) NSArray<ZMAppMarkdownText *> * _Nullable titleMarkedTextArray;
@property (nonatomic, copy) NSArray<ZMAppMarkdownText *> * _Nullable authorMarkedTextArray;
@property (nonatomic, copy) NSArray<ZMAppMarkdownText *> * _Nullable descriptionMarkedTextArray;
@property (nonatomic, copy) NSString * _Nullable appID;
@property (nonatomic, copy) NSString * _Nullable actionID;
@property (nonatomic, strong) ZMCBotInlineVideoPreviewAppContext * _Nullable appContext;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZMCustomEmojiModel;

SWIFT_CLASS_NAMED("CustomEmojiPresentationHandler")
@interface ZMCustomEmojiPresentationHandler : NSObject <ZMViewPresentationAttachmentHandlerProtocol>
@property (nonatomic, strong) ZMCustomEmojiModel * _Nonnull emojiModel;
- (nonnull instancetype)initWithEmojiModel:(ZMCustomEmojiModel * _Nonnull)emojiModel OBJC_DESIGNATED_INITIALIZER;
- (NSView * _Nonnull)makeContentViewWithSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)textRepresentation SWIFT_WARN_UNUSED_RESULT;
- (ZMViewPresentationAttachmentType)viewAttachmentType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DLSecurityFileVC")
@interface ZMDLSecurityFileVC : ZMBaseViewController
@property (nonatomic, readonly, copy) NSNibName _Nullable nibName;
@property (nonatomic, copy) void (^ _Nullable onDownloadClicked)(void);
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSNibName _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ZMEmojiHoverView;

SWIFT_CLASS_NAMED("EmojiHoverCellView")
@interface ZMEmojiHoverCellView : ZMBaseTableCellView
@property (nonatomic, readonly, strong) ZMEmojiHoverView * _Nonnull emojiView;
@property (nonatomic, copy) void (^ _Nullable notifyEmojiDeleted)(void);
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class ZMEmojiLabel;

SWIFT_CLASS_NAMED("EmojiHoverView")
@interface ZMEmojiHoverView : ZMBaseView
@property (nonatomic, readonly, strong) ZMEmojiLabel * _Nonnull emojiView;
@property (nonatomic, copy) void (^ _Nullable notifyEmojiDeleted)(void);
@property (nonatomic) BOOL forceDarkMode;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (BOOL)updateWithCustomEmoji:(ZMCustomEmojiModel * _Nullable)customEmoji;
- (BOOL)updateWithUnicodeEmoji:(NSString * _Nullable)unicodeEmoji;
- (void)refreshCustomEmojiErrorState;
@end


SWIFT_CLASS_NAMED("EmojiLabel")
@interface ZMEmojiLabel : NSView
@property (nonatomic, copy) void (^ _Nullable notifyEmojiShowed)(void);
@property (nonatomic, copy) void (^ _Nullable notifyEmojiDeleted)(void);
@property (nonatomic) BOOL forceDarkMode;
@property (nonatomic) CGFloat fontSize;
@property (nonatomic) CGFloat imageSize;
@property (nonatomic, readonly, strong) ZMCustomEmojiModel * _Nullable customEmoji;
@property (nonatomic, readonly, copy) NSString * _Nullable unicodeEmoji;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)updateWithCustomEmoji:(ZMCustomEmojiModel * _Nullable)customEmoji;
- (void)updateWithUnicodeEmoji:(NSString * _Nullable)unicodeEmoji;
@end

@class ZMEmojiModel;

SWIFT_CLASS_NAMED("EmojiStorage")
@interface ZMEmojiStorage : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZMEmojiStorage * _Nonnull shared;)
+ (ZMEmojiStorage * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSArray<ZMEmojiModel *> *> * _Nonnull emojisSortByCategory;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, ZMEmojiModel *> * _Nonnull unicode2EmojiMap;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSArray<ZMEmojiModel *> * _Nonnull)emojiModelsFor:(NSArray<NSString *> * _Nonnull)unicodes SWIFT_WARN_UNUSED_RESULT;
- (ZMEmojiModel * _Nullable)fuzzySearchModelFor:(NSString * _Nonnull)unicode SWIFT_WARN_UNUSED_RESULT;
@end

@class NSSearchField;
@class ZMChatAlwaysOverlayScrollView;
@class ZMCollectionView;
@class NSTextField;
@class NSProgressIndicator;

SWIFT_CLASS_NAMED("GiphyView")
@interface ZMGiphyView : ZMBaseView
@property (nonatomic, strong) NSSearchField * _Nonnull searchField;
@property (nonatomic, strong) ZMChatAlwaysOverlayScrollView * _Nonnull scrollView;
@property (nonatomic, readonly, strong) ZMCollectionView * _Nonnull collectionView;
@property (nonatomic, readonly, strong) NSTextField * _Nonnull errorTextField;
@property (nonatomic, readonly, strong) NSProgressIndicator * _Nonnull loadingIndicator;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)showLoading;
- (void)stopLoading;
- (void)showErrorWithString:(NSString * _Nonnull)string;
@end


SWIFT_CLASS_NAMED("ImagePresentationHandler")
@interface ZMImagePresentationHandler : NSObject <ZMViewPresentationAttachmentHandlerProtocol>
@property (nonatomic, copy) NSString * _Nonnull imagePath;
@property (nonatomic, copy) NSString * _Nonnull placeholder;
@property (nonatomic, copy) NSString * _Nonnull url;
- (nonnull instancetype)initWithImagePath:(NSString * _Nonnull)imagePath placeholder:(NSString * _Nonnull)placeholder url:(NSString * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)textRepresentation SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)imageURL SWIFT_WARN_UNUSED_RESULT;
- (NSView * _Nonnull)makeContentViewWithSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (ZMViewPresentationAttachmentType)viewAttachmentType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ZMInputViewExternalBannerStyle : NSInteger;
@protocol ZMInputViewExternalBannerProtocol;
@protocol ZMInputViewMemberCountBannerProtocol;

SWIFT_CLASS_NAMED("InputViewBannerHelper")
@interface ZMInputViewBannerHelper : NSObject
+ (NSView <ZMInputViewExternalBannerProtocol> * _Nonnull)externalBannerViewWithStyle:(enum ZMInputViewExternalBannerStyle)withStyle SWIFT_WARN_UNUSED_RESULT;
+ (NSView <ZMInputViewMemberCountBannerProtocol> * _Nonnull)memberCountBannerViewWithCount:(NSUInteger)withCount SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL_NAMED("InputViewBannerProtocol")
@protocol ZMInputViewBannerProtocol
@property (nonatomic, readonly) CGFloat contentHeight;
@property (nonatomic) NSUInteger count;
@end


SWIFT_PROTOCOL_NAMED("InputViewExternalBannerDelegate")
@protocol ZMInputViewExternalBannerDelegate
- (void)inputViewExternalBannerWithDidClick:(NSView <ZMInputViewExternalBannerProtocol> * _Nonnull)view;
@end


SWIFT_PROTOCOL_NAMED("InputViewExternalBannerProtocol")
@protocol ZMInputViewExternalBannerProtocol <ZMInputViewBannerProtocol>
@property (nonatomic, strong) id <ZMInputViewExternalBannerDelegate> _Nullable delegate;
@property (nonatomic) enum ZMInputViewExternalBannerStyle style;
@property (nonatomic) BOOL isSubCMC;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ZMInputViewExternalBannerStyle, "InputViewExternalBannerStyle", open) {
  ZMInputViewExternalBannerStyleDirectMessage = 0,
  ZMInputViewExternalBannerStyleChannel = 1,
  ZMInputViewExternalBannerStyleLargeChannel = 2,
};


SWIFT_PROTOCOL_NAMED("InputViewMemberCountBannerProtocol")
@protocol ZMInputViewMemberCountBannerProtocol <ZMInputViewBannerProtocol>
@end


SWIFT_CLASS_NAMED("LoadingWaitVC")
@interface ZMLoadingWaitVC : ZMBaseViewController
@property (nonatomic, copy) NSString * _Nonnull infoText;
@property (nonatomic, copy) void (^ _Nullable cancelAction)(void);
@property (nonatomic, readonly, copy) NSNibName _Nullable nibName;
- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidDisappear;
- (nonnull instancetype)initWithNibName:(NSNibName _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface NSString (SWIFT_EXTENSION(zChatComponent))
- (BOOL)hasEmojis SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEmojiOnly SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasOnlyOneEmoji SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasOnlyOneEmojiPresentableChar SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)removeEmojiWithExcept:(NSArray<ZMEmojiModel *> * _Nullable)except SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC14zChatComponent12PureTextView")
@interface PureTextView : NSTableCellView
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, RTFCodeblockCellType, open) {
  RTFCodeblockCellTypeNormal = 0,
  RTFCodeblockCellTypeHighlighted = 1,
  RTFCodeblockCellTypeDisabled = 2,
};

@class NSImageView;

SWIFT_CLASS_NAMED("RTFCodeblockLanguageItemCell")
@interface ZMRTFCodeblockLanguageItemCell : ZMBaseTableCellView
@property (nonatomic) enum RTFCodeblockCellType languageCellType;
- (void)setLanguageTitle:(NSString * _Nullable)value;
- (NSString * _Nonnull)getLanguageTitle SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isChecked;
@property (nonatomic, strong) NSImageView * _Nonnull checkImageView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (void)updateLayer;
- (BOOL)isAccessibilityElement SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)accessibilityChildren SWIFT_WARN_UNUSED_RESULT;
- (NSAccessibilityRole _Nullable)accessibilityRole SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessibilityRoleDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessibilityLabel SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("StickerView")
@interface ZMStickerView : ZMBaseView
@property (nonatomic, strong) ZMChatAlwaysOverlayScrollView * _Nonnull scrollView;
@property (nonatomic, readonly, strong) ZMCollectionView * _Nonnull collectionView;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SyncStickerView")
@interface ZMSyncStickerView : ZMBaseView
@property (nonatomic, readonly, strong) NSProgressIndicator * _Nonnull progressIndicator;
@property (nonatomic, readonly, strong) NSTextField * _Nonnull syncTip;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("TextListView")
@interface ZMTextListView : ZMBaseView
@property (nonatomic, strong) NSColor * _Nullable itemTextColor;
@property (nonatomic) NSEdgeInsets contentEdge;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull allText;
@property (nonatomic) BOOL hasVerticalScroller;
@property (nonatomic, readonly) NSSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class NSTableView;
@class NSTableColumn;

@interface ZMTextListView (SWIFT_EXTENSION(zChatComponent)) <NSTableViewDataSource, NSTableViewDelegate>
- (NSInteger)numberOfRowsInTableView:(NSTableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSView * _Nullable)tableView:(NSTableView * _Nonnull)tableView viewForTableColumn:(NSTableColumn * _Nullable)tableColumn row:(NSInteger)row SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(NSTableView * _Nonnull)tableView heightOfRow:(NSInteger)row SWIFT_WARN_UNUSED_RESULT;
- (BOOL)tableView:(NSTableView * _Nonnull)tableView shouldEditTableColumn:(NSTableColumn * _Nullable)tableColumn row:(NSInteger)row SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("UnicodeEmojiModel")
@interface ZMUnicodeEmojiModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull emojiName;
@property (nonatomic, readonly, copy) NSString * _Nonnull unicode;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable skins;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull keywords;
/// Emoji name (Skins included) to unicode map
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull emojiName2UnicodeMap;
/// Unicode emoji (Skins included) to emoji name
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull unicode2EmojiNameMap;
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly) NSUInteger hash;
- (NSString * _Nonnull)emojiAtToneIndex:(NSInteger)toneIndex SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEmojiName:(NSString * _Nonnull)emojiName unicode:(NSString * _Nonnull)unicode skins:(NSArray<NSString *> * _Nullable)skins keywords:(NSArray<NSString *> * _Nullable)keywords OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ZMUserSignatureDataDurationType : NSInteger;
@class NSDate;

/// Model object for the user signature, also known as the “personal note”.
SWIFT_CLASS_NAMED("UserSignatureData")
@interface ZMUserSignatureData : NSObject
/// The type of duration setting.
@property (nonatomic) enum ZMUserSignatureDataDurationType durationType;
/// The raw signature content.
/// This contains the plaintext, written by the user.
@property (nonatomic, copy) NSString * _Nullable content;
/// The formatted content, with prepended or appended decorations included.
/// An example of added content is a short string with a link to a contact’s active huddle.
@property (nonatomic, readonly, strong) NSAttributedString * _Nullable calculatedContent;
/// The name of the huddle the user is in, if any.
@property (nonatomic, copy) NSString * _Nullable huddleName;
/// The deep link of the huddle the user is in, if any.
@property (nonatomic, copy) NSString * _Nullable huddleDeepLink;
/// Whether this signature item is a reminder or not.
@property (nonatomic) BOOL isReminder;
/// The starting date of the item.
@property (nonatomic, copy) NSDate * _Nullable start;
/// The end date of the item.
@property (nonatomic, copy) NSDate * _Nullable end;
/// The duration of the item.
/// This is only used for <code>DurationType/hours</code>.
@property (nonatomic) NSTimeInterval duration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The available user-configurable duration settings.
typedef SWIFT_ENUM_NAMED(NSInteger, ZMUserSignatureDataDurationType, "DurationType", open) {
  ZMUserSignatureDataDurationTypeAlways = 0,
  ZMUserSignatureDataDurationTypeCustom = 1,
  ZMUserSignatureDataDurationTypeHours = 2,
  ZMUserSignatureDataDurationTypeToday = 3,
  ZMUserSignatureDataDurationTypeThisWeek = 4,
};


SWIFT_CLASS_NAMED("ZCCQueueGroup")
@interface ZCCQueueGroup : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull queueList;
- (nonnull instancetype)initWithName:(NSString * _Nullable)name queueList:(NSArray<NSString *> * _Nullable)queueList OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZMFooterStatus, open) {
  ZMFooterStatusNormal = 0,
  ZMFooterStatusLoading = 1,
  ZMFooterStatusError = 2,
};


SWIFT_CLASS("_TtC14zChatComponent31ZMGroupInviteConsentRequestInfo")
@interface ZMGroupInviteConsentRequestInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull sessionID;
@property (nonatomic, copy) NSString * _Nonnull sessionName;
@property (nonatomic, copy) NSString * _Nonnull orgName;
@property (nonatomic, copy) NSString * _Nonnull actionOwnerName;
@property (nonatomic) BOOL autoTrustOrg;
- (nonnull instancetype)initWithSessionID:(NSString * _Nonnull)sessionID sessionName:(NSString * _Nonnull)sessionName orgName:(NSString * _Nonnull)orgName actionOwnerName:(NSString * _Nonnull)actionOwnerName autoTrustOrg:(BOOL)autoTrustOrg OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSessionID:(NSString * _Nonnull)sessionID sessionName:(NSString * _Nonnull)sessionName orgName:(NSString * _Nonnull)orgName actionOwnerName:(NSString * _Nonnull)actionOwnerName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol ZMInviteConsentRequestViewControllerDelegate;

SWIFT_CLASS("_TtC14zChatComponent36ZMInviteConsentRequestViewController")
@interface ZMInviteConsentRequestViewController : NSViewController
@property (nonatomic, strong) ZMGroupInviteConsentRequestInfo * _Nullable request;
@property (nonatomic, weak) id <ZMInviteConsentRequestViewControllerDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSNibName _Nullable nibName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRequest:(ZMGroupInviteConsentRequestInfo * _Nonnull)request OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)loadView;
- (nonnull instancetype)initWithNibName:(NSNibName _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP14zChatComponent44ZMInviteConsentRequestViewControllerDelegate_")
@protocol ZMInviteConsentRequestViewControllerDelegate
- (void)onSuccessfulConsentResponse:(ZMInviteConsentRequestViewController * _Nonnull)sender didConsent:(BOOL)didConsent;
- (void)onConsentRequestRemoval:(ZMInviteConsentRequestViewController * _Nonnull)sender sessionID:(NSString * _Nonnull)sessionID;
@end


SWIFT_PROTOCOL("_TtP14zChatComponent16ZMLoadableFooter_")
@protocol ZMLoadableFooter
- (void)updateFooterWithStatus:(enum ZMFooterStatus)status;
@end


SWIFT_CLASS("_TtC14zChatComponent21ZMNoCustomEmojiFooter")
@interface ZMNoCustomEmojiFooter : ZMBaseView <NSCollectionViewElement>
@property (nonatomic) BOOL forceDarkMode;
@property (nonatomic, copy) void (^ _Nullable addEmojiWindowDidOpen)(void);
@property (nonatomic) ZMCustomEmojiSource source;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14zChatComponent16ZMViewMoreFooter")
@interface ZMViewMoreFooter : ZMBaseView <NSCollectionViewElement>
@property (nonatomic) BOOL forceDarkMode;
@property (nonatomic, copy) void (^ _Nullable viewMoreHandler)(void);
@property (nonatomic) enum ZMFooterStatus status;
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


@interface ZMViewMoreFooter (SWIFT_EXTENSION(zChatComponent)) <ZMLoadableFooter>
- (void)updateFooterWithStatus:(enum ZMFooterStatus)status;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
